---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/kiwi-class-",
  out.width = "100%"
)
options(crayon.enabled = NULL)
```

# Kiwi Class API

[elbird][elbird]는 간단하게 바로 사용할 수 있는 함수 api(`tokenize()`, `analyze()`, `split_into_sents()`)를 제공합니다.
하지만 더욱 복잡한 동작에 대한 요구는 당연히 있겠죠.
그래서 `Kiwi` 클래스 api를 제공합니다.

```{R}
library(elbird)
kw <- Kiwi$new()
kw
```

[kiwi][kiwi]는 분석기 모델을 3가지로 제공합니다. `small`, `base`, `large`,
함수 api에서는 `small`을 사용하고 있으며, 아직 변경 방법을 제공하고 있지 않습니다.

`Kiwi` 클래스는 생성시 크기를 지정할 수 있습니다.

```{r}
kwl <- Kiwi$new(model_size = "large")
kwl
```

이렇게 만든 `Kiwi`의 객체는 몇 가지 메소드를 제공합니다.
우선 당연히 `tokenize()` 와 `analyze()`를 제공합니다.

```{r}
kw$tokenize("안녕하세요.")
kw$analyze("안녕하세요.")
```

그리고 사용자의 추가 단어를 등록할 수 있습니다.

```{r}
kw$tokenize("박박사입니다.")
kw$add_user_word("박박사", Tags$nnb, 0)
kw$tokenize("박박사입니다.")
```



[kiwipiepy]: https://github.com/bab2min/kiwipiepy
[kiwi]: https://github.com/bab2min/Kiwi
[elbird]: https://mrchypark.github.io/elbird/index.html
