# Generated by cpp11: do not edit by hand

kiwi_version_ <- function() {
  .Call(`_elbird_kiwi_version_`)
}

kiwi_error_ <- function() {
  .Call(`_elbird_kiwi_error_`)
}

kiwi_clear_error_ <- function() {
  invisible(.Call(`_elbird_kiwi_clear_error_`))
}

kiwi_init_ <- function(model_path, num_threads, options) {
  .Call(`_elbird_kiwi_init_`, model_path, num_threads, options)
}

kiwi_analyze_ <- function(handle_ex, text, top_n, match_options) {
  .Call(`_elbird_kiwi_analyze_`, handle_ex, text, top_n, match_options)
}
